LOAD DATA LOCAL INFILE 'database/Tenants.csv'
INTO TABLE TENANTS
FIELDS TERMINATED BY ','
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE 'database/Buildings.csv'
INTO TABLE BUILDINGS
FIELDS TERMINATED BY ','
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE 'database/Workers.csv'
INTO TABLE WORKERS
FIELDS TERMINATED BY ','
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE 'database/Apartments.csv'
INTO TABLE APARTMENTS
FIELDS TERMINATED BY ','
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE 'database/Maintenance_Issues.csv'
INTO TABLE MAINTENANCE_ISSUES
FIELDS TERMINATED BY ','
IGNORE 1 ROWS;