DROP DATABASE apartmentDB;

CREATE DATABASE apartmentDB;

USE apartmentDB;

CREATE TABLE TENANTS (
    ID int NOT NULL AUTO_INCREMENT,
    FIRST_NAME varchar(15) NOT NULL,
    LAST_NAME varchar(15) NOT NULL,
    PHONE_NUMBER varchar(15) NOT NULL,
    EMAIL varchar(40) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE BUILDINGS(
    ID INT NOT NULL AUTO_INCREMENT,
    PHONE VARCHAR(15),
    EMAIL VARCHAR(40),
    NAME VARCHAR(50),
    PRIMARY KEY(ID)
);

CREATE TABLE APARTMENTS(
    ID INT NOT NULL AUTO_INCREMENT,
    UNIT_NUMBER INT NOT NULL,
    OCCUPANT_ID INT,
    BUILDING_ID INT,
    PRIMARY KEY (ID),
    FOREIGN KEY (OCCUPANT_ID) REFERENCES TENANTS(ID),
    FOREIGN KEY (BUILDING_ID) REFERENCES BUILDINGS(ID)
);


CREATE TABLE WORKERS(
    ID INT AUTO_INCREMENT,
    NAME VARCHAR(30),
    PHONE VARCHAR(15),
    EMAIL VARCHAR(40),
    PRIMARY KEY (id)
);

CREATE TABLE MAINTENANCE_ISSUES(
    ID INT AUTO_INCREMENT,
    STATUS boolean,
    DATE DATE,
    WORKER_ID INT,
    APT_ID INT,
    BUILDING_ID INT,
    FOREIGN KEY (WORKER_ID) REFERENCES WORKERS(ID),
    FOREIGN KEY (BUILDING_ID) REFERENCES BUILDINGS(ID),
    FOREIGN KEY (APT_ID) REFERENCES APARTMENTS(ID),
    PRIMARY KEY (ID)
);


LOAD DATA LOCAL INFILE 'database/Tenants.csv'
INTO TABLE TENANTS
FIELDS TERMINATED BY ','
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE 'database/Buildings.csv'
INTO TABLE BUILDINGS
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE 'database/Workers.csv'
INTO TABLE WORKERS
FIELDS TERMINATED BY ','
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE 'database/Apartments.csv'
INTO TABLE APARTMENTS
FIELDS TERMINATED BY ','
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE 'database/Maintenance_Issues.csv'
INTO TABLE MAINTENANCE_ISSUES
FIELDS TERMINATED BY ','
IGNORE 1 ROWS;