DROP DATABASE apartmentDB;

CREATE DATABASE apartmentDB;

USE apartmentDB;

CREATE TABLE TENANTS (
    ID int NOT NULL AUTO_INCREMENT,
    FIRST_NAME char(20) NOT NULL,
    LAST_NAME char(20) NOT NULL,
    PHONE_NUMBER varchar(15) NOT NULL,
    EMAIL varchar(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE APT_COMPLEXS(
    ID INT NOT NULL AUTO_INCREMENT,
    PHONE VARCHAR(15),
    EMAIL VARCHAR(50),
    NAME VARCHAR(100),
    PRIMARY KEY(ID)
);

CREATE TABLE APARTMENTS(
    ID INT NOT NULL AUTO_INCREMENT,
    UNIT_NUMBER INT,
    OCCUPANT INT,
    PARKING BOOLEAN,
    WASHER_DRYER BOOLEAN,
    APT_COMPLEX INT,
    PRIMARY KEY (ID),
    FOREIGN KEY (OCCUPANT) REFERENCES TENANTS(ID),
    FOREIGN KEY (APT_COMPLEX) REFERENCES APT_COMPLEXS(ID)
);


CREATE TABLE WORKERS(
    ID INT AUTO_INCREMENT,
    NAME VARCHAR(30),
    PHONE VARCHAR(15),
    EMAIL VARCHAR(50),
    PRIMARY KEY (id)
);

CREATE TABLE APARTMENT_PROBLEMS(
    TICKET_NUMBER INT AUTO_INCREMENT,
    STATUS boolean,
    DATE DATE,
    WORKER INT,
    APT_ID INT,
    FOREIGN KEY (WORKER) REFERENCES WORKERS(ID),
    FOREIGN KEY (APT_ID) REFERENCES APARTMENTS(ID),
    PRIMARY KEY (TICKET_NUMBER)
);



LOAD DATA LOCAL INFILE 'database/tenants.csv'
INTO TABLE TENANTS
FIELDS TERMINATED BY ','
IGNORE 1 ROWS;

