
CREATE TABLE TENANTS (
    ID int NOT NULL AUTO_INCREMENT,
    FIRST_NAME char(20) NOT NULL,
    LAST_NAME char(20) NOT NULL,
    PHONE_NUMBER varchar(10) NOT NULL,
    EMAIL varchar(30) NOT NULL,
    PRIMARY KEY (id)
);



CREATE TABLE APARTMENTS(
    ID INT NOT NULL AUTO_INCREMENT,
    UNIT_NUMBER INT,
    OCCUPANT INT,
    PARKING BOOLEAN,
    WASHER_DRYER BOOLEAN,
    APT_COMPLEX INT,
    PRIMARY KEY (ID),
    FOREIGN KEY (OCCUPANT) REFERENCES TENANTS(ID),
    FOREIGN KEY (APT_COMPLEX) REFERENCES APT_COMPLEXS(ID)
);



CREATE TABLE APT_COMPLEXS(
    ID INT NOT NULL AUTO_INCREMENT,
    PHONE VARCHAR(10),
    EMAIL VARCHAR(10),
    PRIMARY KEY(ID)
);




CREATE TABLE APARTMENT_PROBLEMS(
    TICKET_NUMBER INT AUTO_INCREMENT,
    STATUS boolean,
    DATE DATE,
    WORKER INT,
    APT_ID INT,
    FOREIGN KEY (WORKER) REFERENCES WORKERS(ID),
    FOREIGN KEY (APT_ID) REFERENCES APARTMENTS(ID),
    PRIMARY KEY (TICKET_NUMBER)
);

CREATE TABLE WORKERS(
    ID INT AUTO_INCREMENT,
    NAME VARCHAR(20),
    PHONE VARCHAR(20),
    EMAIL VARCHAR(20),
    PRIMARY KEY (id)
);


INSERT INTO APARTMENTS (UNIT_NUMBER,OCCUPANT,PARKING,WASHER_DRYER,APT_COMPLEX) VALUES(1,1,true,false,1);
INSERT INTO TENANTS (FIRST_NAME,LAST_NAME,PHONE_NUMBER,EMAIL) VALUES("Allison", "Schultz", "4982847412", "ahshd@gmail.com");
INSERT INTO APT_COMPLEXS (PHONE, EMAIL) VALUES("1234538513", "AK@gmail.com");
INSERT INTO WORKERS (NAME, PHONE,EMAIL) VALUES("Doug", "2342342111" ,"doug@gmail.com");
INSERT INTO APARTMENT_PROBLEMS (STATUS,DATE, WORKER, APT_ID) VALUES(true, "2021-08-18",1,1 );


